export const FETCHING_QUESTIONS_PENDING = "FETCHING_QUESTIONS_PENDING";
export const FETCHING_QUESTIONS_SUCCESS = "FETCHING_QUESTIONS_SUCCESS";
export const FETCHING_QUESTIONS_FAILED = "FETCHING_QUESTIONS_FAILED";
export const QUESTION_ANSWERED_CORRECT = "QUESTION_ANSWERED";
export const QUESTION_ANSWERED_WRONG = "QUESTION_ANSWERED";
